# -*- coding: utf-8 -*-
"""Decision making Nadzirah DAY 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_299jSx-PF1P6o-q07vsJ2t4OvbAPeg
"""

# Decision making
# A.K.A Conditional Statements / working with conditions

# CONTOH CONDITION: you are designing gaming applicatoion
# age must be over 18
# user should provide valid username and password

# if
# if else
# if elif else
# kesemua ni reserved keyword
# make sure guna huruf kecil

# Decision Making
# Conditional Statements / Working With Conditions

# is the ability of a program to execute the block of code
# only when the condition is TRUE

# if
# if else
# if elif else

# if statement
# what if will do?

# if will check the condition First
# if the condition is TRUE then only it will allow python
# interpreter to execute the code

# Syntax
# very important
# if is a reserved keyword
# if condition:
#  block of code
# only then will execute ( to carry out, perform, )
age = 21
if age>=18:
    print('Eligible For A Driving License')
# nampak tak ada space dekat print? python auto provide space for you
# wide space in python known as indentation
# apa tu indentention?
# used to define the body of the IF
# apa jadi kalau tiada space after : colon?
# akan jadi error

    age = 16
if age>=18:
    print('Eligible For A Driving License')
    # CARA BACA:
    # variable (age) is 16
    # if age is greater than 18 colon
    # hasil akan jadi macam diatas

age = 15
if age<=18:
      print("Hi kids!")
      # Dibaca if age lesser than 18 colon
      # print hi kids

num = int(input('Enter Any Number : '))
if num%2==0:
  # cara baca dia "If num modulo 2 equals equals to 0
  # apa maksud dia?

    print('Checking The Number.....')
    print('Number Is Even')
    print('Still I am in IF')
    print('Me Too')
# setiap kali kita new line, kita still dalam IF body
# jadi kalau nak exit dari IF body kena manually delete space sampai tiada space left
# only then your new line will be treated as new code and NOT IF BODY
# this is what we call rule of indentation
print('Rest of the code')

# Task
# Print The Largest

a = 19
b = 45
c = 27
d = 141
e = 67

largest = 0

if a>largest:              #  19>0 (t)
    largest = a            # largest = 19
if b>largest:              # 45>19 (t)
    largest = b            # largest = 45
if c>largest:              # 27>45 (f)
    largest = c
if d>largest:             # 141>45(t)
    largest = d           # largest = 141
if e>largest:             # 67>141 (f)
    largest = e

print(f'Largest is : {largest}')

# if else
age = 26
if age>=18:
    print('Welcome User')
    print('Game is loading....')
    print('Please Wait')
else:
    print('Age Restrictions.')
    print('Age Should Be Above Or Equal To 18')

num = int(input('Enter Any Number : '))
if num%2==0:
    print('Even Number')
else:
    print('Odd Number')

num = int(input("Nombor tu genap ke ganjil?\n Cuba masukkan nombor dekat sini saya bantu : "))
if num%2==0:
  print("Genap ni bro macam kita berdua😜 ")
else:
  print("Ganjil ni bro macam bro yang single dan sendiri😝")

age = int(input("Enter your age : "))
if age<=18:
  print("You are not allowed here kid, bye")
else:
  print("Hey there buddy!")

name = str(input("Whats your name? : "))
age = int(input("Enter your age : "))
if age<=18:
  print("You are not allowed here kid, bye")
else:
  print("Hey there buddy!")
  #saya buat sendiri! hihi

name = str(input("Whats your name? : "))
age = int(input("Age please : "))
if age <=18:
  print("You are not allowed here kid, bye")
else:
  print("Hello there buddy!")
  print('Game is loading....')
  print('Please Wait')

# One Liner if else sebutan dia one lainer if else
# ternary operator
# maksudnya instead of tulis 5-6 line, semua ni boleh dipendekkan jadi 1 line sahaja

# if_condition_is_true  if  condition  else value_if_condition_is_false
# professional ways of programming
num = int(input('Enter Any Number : '))
result = 'Even Number' if num%2==0 else 'Odd Number'
print(result)

age = 16
res = 'Eligible For License' if age>=18 else 'Not Eligible For A License'
print(res)
# Benda ni hanya boleh guna untuk if, else sahaja meaning 2 conditions sahaja
# Most of the time guna yang biasa bukan ternary operator

# if elif else
# working with multiple conditions

# at a time only one block of code will be executed
# Boleh letak banyak banyak conditionss
# Dalam case ni, python baca line by line
# dia baca satu per satu line, kalau satu condition is true dia terus kata true dan exit if esif dan else
# bila dia baca semua?
# all dalam if elif else sahaja
# kalau condition if dah true, python tak baca line lain, dia terus exit
# contoh kalau line first =FALSE, baru dia baca ilif
# kalau elif return as False, baru dia baca else
# this is how if elif else works
num = int(input('Enter Any Number : '))
if num<0:
    print('Negative Number')
elif num==0:
    print('Number is Zero')
else:
    print('Positive Number')

print("Grading Allotment Application")
marks = int(input("Enter Your Marks :"))
if marks<=100 and marks>=85:  # 100 - 85
  print("Grade A")
elif marks<84 and marks>=75:   # 84 - 75
  print("Grade B")
elif marks<74 and marks>=60:
  print("Grade C")
elif marks<59 and marks>=40:
  print("Grade D")
elif marks<39 and marks>=0:
  print("Gagal")
else:
  print("Invalid Score")

print("Jom check gred korang")
marks = int (input("Masuk markah dekat sini : "))
if marks<=100 and marks >=85:
  print("WOW! A. Congrats!👌")
elif marks<=84 and marks >=75:
  print("B. Nice!🤙")
elif marks<=74 and marks >=60:
  print("C. Keep up!")
elif marks<=59 and marks >=40:
  print("DANG, try again bruh 👩🏿‍🦯")
else:
  print("What are you doing dawg 💔\n Invalid marks")

# Chained Comparison
# help us to define a range
# Lower Limit <=  value   <=  Upper Limit
# kena tulis smaller value dulu baru tulis bigger value

print("Grading Allotment Application")
marks = int(input("Enter Your Marks :"))   # 83
# dibaca kurang daripada atau sama dengan
# here 85 <= marks <= 100 this expression means
#  a.) the value is less than or equal to 100    c1     is 93 <=100 (t)
#  b.) 85 means that I am less the define value  c2     is 85 is less than 93 (t)
# tulis nilai kecil dulu baru bigger value
if 85 <= marks <= 100:       #  83<=100 (t)   85 is it less than 83 (f)
    print('Grade A')
elif 75 <= marks <= 84:      # 83<=84  (t)    75 is it less than 83 (t)
    print('Grade B')

# Task
print("Hello! Welcome to BMI CALCULATOR")
name = str(input("Hi, whats your name? : "))
weight = int(input("Weight please : "))
height = int(input("Height? : "))
bmi = weight/ meters* meters
if  <= marks <= 29.9:
    print('Underweight')
elif 75 <= marks <= 84:
    print('Grade B')
else:
  print("Oops, obese")

