# -*- coding: utf-8 -*-
"""GuessANumberGame_Nadzirah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AA3lD5cn13FNo2rpq5wejtjgqm5jx4f6
"""

import random

def guess_the_number():
    secret_number = random.randint(1, 100)
    attempts = 0
    print("Welcome to the Guess the Number game!")
    print("I'm thinking of a number between 1 and 100.")

    while True:
        try:
            guess = int(input("Enter your guess: "))
            attempts += 1

            if guess < secret_number:
                print("Too low! Try again.")
            elif guess > secret_number:
                print("Too high! Try again.")
            else:
                print(f"Congratulations! You guessed the number {secret_number} in {attempts} attempts!")
                break
        except ValueError:
            print("Invalid input. Please enter a whole number.")

if __name__ == "__main__":
    guess_the_number()

