# -*- coding: utf-8 -*-
"""Loops NADZIRAH Pt 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lhMQ2j2T6b6mrOy6VppuODNrCWJ19w6
"""

# Loops ibarat copy paste so kita takpayah tulis print banyak kali
 # Tinggal guna loops je

# Loops in Python are used to repeat a block of code multiple times without
# writing the same code again and again.

# Loops help us repeat tasks efficiently and smartly.

# A loop is a control structure that repeats a block of code until a condition is met.
 # loops ada 2 bahagian iaitu for and while
# for and while = loops

# for loop
# for Loop is used to iterate(ulang)sebutan aiterate over a Sequence = str, tuple[collection of data values]
# for is a reserved keyword in python

# syntax
# 1. tulis for
# 2. define one variable, bagilah nama apa apa pun
# make sure ikut rules untuk variable. apa rulenya?
# - case sensitive
# - tak boleh guna nombor
# - tak boleh guna reserved keyword python


# for iterable_variable in Sequence:

# variable dalam loops kita guna iterable_variable
# perasan tak dalam line diatas ada "for" dan ada membership operator "in"
# lepastu kena ada colon:
# akan ada rules of indentation (ada jarak auto)
#   block of code

# AFTER EVERY ITERATION BODY OF FOR LOOP
# WILL BE EXECUTED=completed

for i in "Python":
    print(i)
# Contoh macam atas ni
# Ada for
# variable
# ada in
# ada sequence
# ada colon :
# ada rule of indentation (auto jarak)
# baru print(i) = i merujuk pada variable

product_prices = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50
tax = 2.05

# client: "give me a final price list after adding text"
print(product_prices[0] + tax)
print(product_prices[1] + tax)
print(product_prices[2] + tax)
print(product_prices[3] + tax)
print(product_prices[4] + tax)

# Tapi cara ni less effective, dan ini kita guna indexing
# kalau shoppe ada milions of products takkan kita nak tulis satu satu sampai milions
# here come the loops in action

# cara paling mudah:
# kita guna for loops
product_prices = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50 , 51 , 52 , 53
tax = 2.05

for i in product_prices:
    print(i + tax)

numbers = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50 , 51 , 52 , 53
# print only the even numbers

for x in numbers:
    if x%2==0:
        print(x)

emp_names = 'Alex' , 'John' , 'Smith' , 'amir' , 'Tina' , 'mathews' , 'Anders' , 'Juliet' , 'Allan' , 'ashley'

# print only those names where the first letter startswith 'A' or 'a'

for i in emp_names:
    if i.startswith(('A','a')):
        print(i)

# cubaan saya buat sendiri
names_random = "Lydia", "Lamb" ,"Kaysen", "Rivera","Lillian", "Friedman","Darwin", "Esparza","Ramona Aguirre"
for i in names_random:
  if i.startswith(("l","L")):
    print(i)

# Task:
# Kena print even number
numbers = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50 , 51 , 52 , 53
# print only the even numbers

for x in numbers:
    if x%2==0:
        print(x)

numbers = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50 , 51 , 52 , 53
for i in numbers:
  if i%2==1:
    print(i)

# Letak satu variable
# Cara tulis for loops syntax
# for
# iterable_variable (i)
# in (operator)
# variable
# colon:

# if
# (i) iterable variable
# %
# 2
# == equal equal to
# 1 =condition
# colon:

# print (i)

# range()
# it's a built-in function and it is used to generate
# a sequence of Integer Numbers

# a.) range(x)
# it is used to generate a sequence of Integer Numbers
# starting from Zero till x-1

print(list(range(10)))

print(list(range(12)))
# untuk dapatkan sequence 0-11 kena tulis list dalam range
# kalau tak tulis list dia tak kan return as a list
# kenapa return sampai 11 shaja?
# sebab memang range akan bagi list of int sequence dan nombor jujung tu -1

# cubaan saya buat range
print(list(range(5)))
# cara tulis syntax
# print
# parantheses()
# list
# parantheses()
# range
# parantheses(int)
# first value should be smaller, second value should be greater
# kalau tulis bigger value baru smaller value result dia akan jadi nothing

# b.) range(x,y)
# it is used to generate a sequence of Integer Numbers
# starting from x till y-1
# first value should be smaller, second value should be greater
# kalau tulis bigger value baru smaller value result dia akan jadi nothing
print(list(range(1,11)))

print(list(range(2,10)))
# result akan jadi sequence of integer dari nombor 2 sampai 9
# sebab hujung tu akan tolak 1
# result:

# c.) range(x,y,stepCount/Interval)
# it is used to generate a sequence of Integer Numbers
# starting from x till y-1 based on stepCount
# stepCount/Interval akan ambil int ke-berapa yang kita tulis dan repeat nombor tu sampai habis
# faham ke?
# tengok macam bawah ni
print(list(range(1,11,3)))

# print all the even numbers till 100 using range
print(list(range(0,101,2)))

# Cubaan saya untuk buat range gunakan stepCount/Interval
print(list(range(1,61,4)))
# result akan jadi macam dekat bawah

# print all the even numbers till 100 using range exercise
# output:
print(list(range(0,101,2)))

# using for and range()
# behind the scene
for i in range(1,11):   # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    print(f"{i} Python")

num = 13

for i in range(1,11):             # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    print(f"{num}x{i}={num*i}")

# NESTED FOR LOOP
# dua loops dalam satu syntax
# OUTER LOOP WILL WAIT UNTIL INNER LOOP FINISHES THE EXECUTION

for c in ['red' , 'blue' , 'green']:      # OUTER FOR LOOP
    for v in ['car' , 'bike' , 'bus']:    # INNER FOR LOOP
        print(c,v)

# while loop
# used to repeat a block of code several times
# until a certain condition is met

# syntax while loop dan for loop sangat berbeza
# initialization      [optional]
# meaning the preparation of a computer or similar device for operation, in which diagnostic tests are run and the operating system is loaded.

# while condition/expression:
#   code to be executed
#   increment / decrement  [optional]

# WHILE WILL CHECK THE CONDITION FIRST
# IF THE CONDITION IS TRUE , WHILE WILL EXECUTE ITS BODY
# AFTER WHILE FINISH EXECUTING THE BODY , CONDITION WILL BE CHECKED AGAIN
# IF THE CONDITION IS TRUE , WHILE WILL AGAIN EXECUTE ITS BODY

i = 1                  # 1ST ITER  i = 1    2ND ITER  i = 2     3RD ITER  i = 3   4TH ITER
while i<=3:            # 1<=3 (t)            2<=3 (t)            3<=3 (t)         4<=3 (FALSE)
    print(i)           # 1                   2                   3
    i = i + 1          # i = 1 + 1 ==> 2     i = 2 + 1 ==> 3     i = 3 + 1 ==> 4

# i = iteration_variable
i = 2 #value yang boleh berubah
while i<=12: #dibaca while i lesser or equavalant to 2 colon:
  print(i)
  i = i + 2

# PRINT MATHEMATICAL TABLE OF A NUMBER 13
# USING WHILE LOOP

num = 13
i = 1
while i<=10:
    print(f'{num}X{i}={num*i}')
    i = i + 1

# USE FOR LOOP WHEN THE NUMBER OF ITERATIONS ARE FIXED
# OR USE FOR LOOP WHEN YOU ARE LOOKING FOR PERFORMING AN ITERATION

# USE WHILE LOOP WHEN THE NUMBER OF ITERATIONS ARE NOT FIXED
# WHEN THE NUMBER OF ITERATIONS ARE NOT KNOWN