# -*- coding: utf-8 -*-
"""Nested List Comprehension Nadzirah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMQVoYw5XRx1ZpxLhfVNOjaxXFgyrUSz
"""

# Nested List Comprehension
# it's a compact and pythonic way to create a new List
# it's like creating a new list in a single line of code

numbers = [2,3,4,5,6,7,8,9,10]
# create a new list showing the square of all number
square = []
for i in numbers:
    square.append(i*i)
print(square)

numbers = [2,3,4,5,6,7,8,9,10]
square = [i*i for i in numbers]
print(square)

# nested list comprehension
# newlist = [expression forLoop if condition] use this syntax

# without nested list comprehension
numbers = [2,3,4,5,6,7,8,9,10,11,12,13,14,15]
# create a new List showing all even numbers
even = []
for i in numbers:
    if i%2==0:# cara baca if i mod 2 even even 0
        even.append(i)
print(even)

numbers = [2,3,4,5,6,7,8,9,10,11,12,13,14,15]
even = [i for i in numbers if i%2==0]
print(even)

# task :solve this without using nested listed comprehension
#Q: create a new list showing marks >=50

marks = [56,34,89,76,90,43,21,15,18,50,45,89,76]
newMarks = []
for i in marks:
    if i >= 50:
        newMarks.append(i)
print(newMarks)

# Answer if we solve the task using nested listed comprehensiom
# perhatikan perbezaan pada syntax
marks = [56,34,89,76,90,43,21,15,18,50,45,89,76]
newMarks = [i for i in marks if i >= 50]
print(newMarks)

names = ['Amelia Johnson', 'Benjamin Carter', 'Chloe Davis', 'David Miller',
         'Eleanor Rodriguez', 'Franklin Smith', 'Grace Wilson', 'Henry Thompson',
         'Isabella Martinez', 'Jack Anderson']
newname = []
for n in names:
    if n.startswith(('A','F','J')):  # if n[0]=='A' or n[0]=='F' or n[0]=='J'
        newname.append(n)
print(newname)

names = ['Amelia Johnson', 'Benjamin Carter', 'Chloe Davis', 'David Miller',
         'Eleanor Rodriguez', 'Franklin Smith', 'Grace Wilson', 'Henry Thompson',
         'Isabella Martinez', 'Jack Anderson']
newname = [n for n in names if n.startswith(('A','F','J'))]
print(newname)